// <auto-generated />
using System;
using WolfStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WolfStore.Api.Data.Migrations
{
  [DbContext(typeof(WolfStoreDbContext))]
  partial class WolfStoreDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("WolfStore.Api.Data.Entities.Product", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd();

            b.Property<string>("Description");

            b.Property<DateTimeOffset>("IntroducedAt");

            b.Property<string>("Name")
                      .HasMaxLength(100);

            b.Property<string>("PhotoFileName")
                      .HasMaxLength(100);

            b.Property<decimal>("Price")
                      .HasColumnType("decimal(18,2)");

            b.Property<int>("Rating");

            b.Property<int>("Stock");

            b.Property<int>("Type");

            b.HasKey("Id");

            b.ToTable("Products");
          });
#pragma warning restore 612, 618
    }
  }
}
